name: Publish

on: [push]

jobs:
  publish:
    name: Publish package on NPM

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install

      - run: yarn build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: false
          access: 'public'
          tag: 'latest'
