name: Publish

on: [push]

jobs:
  build:
    name: Build on Node 18

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
      - run: npm set registry https://www.npmjs.com/package/@busshi/telegram-api
      - run: npm set https://www.npmjs.com/package/@busshi/telegram-api:_authToken ${{ secrets.NPM_TOKEN }}
      - run: npm publish --access public
  # publish:
  #   name: Publish package on NPM
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - run: yarn install
  #     - uses: JS-DevTools/npm-publish@v1
  #       with:
  #         token: ${{ secrets.NPM_TOKEN }}
  #   needs: build
